####################################################
#
# Welcome to Redron Jekyll Template
#
# Product Link : https://themeix.com/product/redron-jekyll-template/
# Version : v1.0.0
#
####################################################

# Site settings
title: "Comtraining | Consultorías & Coaching"
email: "info@comtraining.biz"
baseurl: "" # the subpath of your site, e.g. /blog
url: " " # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/logo/logo.png
description: ""
keywords: "coaching, coaching ejecutivo, liderazgo, cambio organizacional, clima organizacional, team building, team learning"
mailclimp: ''
facebook: https://www.facebook.com/Comtrainingpro/
instagram: https://www.instagram.com/comtraining.consulting/
twitter: https://twitter.com/comtraining


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 6
  permalink: '/pages/:num/' # Pages are simple html files
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after:
  extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  categories:
    layouts:
      - 'category.html'
    title: 'Categoría -  :cat'
    permalink: '/categoría/:cat'
  collections:
    layouts:
      - 'category.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'
  tags:
    layouts:
      - 'tag.html'
    title: 'Etiqueta - :tag' # :tag is replaced by the tag name
    permalink: '/etiqueta/:tag'

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/categoría/:name/'

collections:
  services:
    output: true
    permalink: /servicios/:path/
  projects:
    output: true
    permalink: /project/:path/

feed:
  collections:
    posts:
      path: "/index.xml"