# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: 'assets/uploads'
site_url: https://comtraining.netlify.app/
logo_url: https://comtraining.netlify.app/assets/img/logo/logo.png
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Foto principal', name: 'post_image', widget: 'image' }
      - label: "Autor"
        name: "author_name"
        widget: "select"
        options:
          - { label: "Francisco Vallés", value: "Francisco Vallés" }
          - { label: "Anónimo", value: "Anónimo" }
      - { label: '¿Permitir comentarios?', name: 'comments', widget: 'boolean' }
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        min: 1
        summary: '{{fields.name}}'
        field: {label: Nombre, name: name, widget: string}
      - label: "Categorías"
        name: "categories"
        widget: "list"
        min: 1
        summary: '{{fields.name}}'
        field: {label: Nombre, name: name, widget: string}
  - name: 'services'
    label: 'Servicios'
    folder: '_services/'
    extension: 'html'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'service' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Ícono', name: 'icon', widget: 'image' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navegación'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Ítems de navegación'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: text, widget: string }
              - { label: Enlace, name: url, widget: string }
              - label: 'Menú desplegable'
                name: 'submenu'
                widget: 'list'
                fields:
                  - { label: Nombre, name: text, widget: string }
                  - { label: Enlace, name: url, widget: string }
      - label: 'Testimonios'
        name: 'testimonials'
        file: '_data/testimonials.yml'
        fields:
          - label: 'Registros'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen de perfil, name: image, widget: image }
              - { label: Reseña, name: review, widget: text }
              - { label: Cargo, name: designation, widget: string }
              - { label: Rating, name: rating, widget: number }
      - label: 'Miembros del equipo'
        name: 'members'
        file: '_data/team-members.yml'
        fields:
          - label: 'Miembros'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen de perfil, name: img_src, widget: image }
              - { label: Cargo, name: designation, widget: string }
              - { label: Facebook, name: facebook, widget: string }
              - { label: Twitter, name: twitter, widget: string }
              - { label: Instagram, name: instagram, widget: string }
      - label: 'FAQs'
        name: 'faqs'
        file: '_data/faqs.yml'
        fields:
          - label: 'Preguntas frecuentes'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Pregunta, name: question, widget: string }
              - { label: Respuesta, name: answer, widget: text }
      - label: 'Empresas'
        name: 'brands'
        file: '_data/brands.yml'
        fields:
          - label: 'Empresas'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen, name: img_src, widget: image }
              - { label: Enlace, name: link, widget: string }