# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: 'assets/uploads'
site_url: https://comtraining.netlify.app/
logo_url: https://comtraining.netlify.app/assets/img/logo/logo.png
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    sort: 'date:desc'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
      - { label: 'Foto principal', name: 'post_image', widget: 'image' }
      - label: "Autor"
        name: "author_name"
        widget: "relation"
        collection: "authors"
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "name"
      - { label: '¿Permitir comentarios?', name: 'comments', widget: 'boolean' }
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        min: 1
        summary: '{{fields.name}}'
        field: {label: Nombre, name: name, widget: string}
      - label: "Categorías"
        name: "categories"
        widget: "list"
        min: 1
        summary: '{{fields.name}}'
        field: {label: Nombre, name: name, widget: string}
  - name: 'authors'
    label: 'Autores'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Nombre', name: 'name', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'text' }
      - { label: 'Rol', name: 'designation', widget: 'string' }
      - { label: 'Imagen', name: 'profile_image', widget: 'image' }
  - name: 'services'
    label: 'Servicios'
    folder: '_services/'
    extension: 'html'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'service' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Ícono', name: 'icon', widget: 'image' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Url brochure', name: 'brochure_url', widget: 'string' }
      - { label: 'Cita', name: 'quote', widget: 'text' }
      - { label: 'Autor cita', name: 'quote_author', widget: 'string' }
      - { label: 'Subtexto autor cita', name: 'quote_author_subtitle', widget: 'string' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navegación'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Ítems de navegación'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: text, widget: string }
              - { label: Enlace, name: url, widget: string }
              - label: 'Menú desplegable'
                name: 'submenu'
                widget: 'list'
                fields:
                  - { label: Nombre, name: text, widget: string }
                  - { label: Enlace, name: url, widget: string }
      - label: 'Testimonios'
        name: 'testimonials'
        file: '_data/testimonials.yml'
        fields:
          - label: 'Registros'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen de perfil, name: image, widget: image }
              - { label: Reseña, name: review, widget: text }
              - { label: Cargo, name: designation, widget: string }
              - { label: Rating, name: rating, widget: number }
      - label: 'Miembros del equipo'
        name: 'members'
        file: '_data/team-members.yml'
        fields:
          - label: 'Miembros'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen de perfil, name: img_src, widget: image }
              - { label: Cargo, name: designation, widget: string }
              - { label: Linkedin, name: linkedin, widget: string }
      - label: 'FAQs'
        name: 'faqs'
        file: '_data/faqs.yml'
        fields:
          - label: 'Preguntas frecuentes'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Pregunta, name: question, widget: string }
              - { label: Respuesta, name: answer, widget: text }
      - label: 'Empresas'
        name: 'brands'
        file: '_data/brands.yml'
        fields:
          - label: 'Empresas'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Nombre, name: name, widget: string }
              - { label: Imagen, name: img_src, widget: image }
              - { label: Enlace, name: link, widget: string }
      - label: 'Acerca de nosotros'
        name: 'about'
        file: '_data/about.yml'
        fields:
          - { label: Epígrafe, name: header_title, widget: string }
          - { label: Título, name: title, widget: string }
          - { label: Descripción, name: description, widget: text }
          - { label: Imagen, name: image, widget: image }
          - { label: Texto imagen, name: image_text, widget: string }
          - label: 'Listado'
            name: 'main_points'
            widget: 'list'
            fields:
              - { label: Texto, name: text, widget: string }
          - label: 'Cuadros de texto'
            name: 'text_items'
            widget: 'list'
            fields:
              - { label: Texto, name: text, widget: string }
              - { label: Ícono, name: icon, widget: string }
      - label: 'Funcionalidades'
        name: 'feature'
        file: '_data/feature.yml'
        fields:
          - label: 'Secciones'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Epígrafe, name: header_title, widget: string }
              - { label: Título, name: title, widget: string }
              - { label: Descripción, name: description, widget: text }
              - { label: Imagen, name: image, widget: image }
              - { label: Imagen superpuesta, name: over_image, widget: image }
              - label: "Dirección imagen"
                name: "image_direction"
                widget: "select"
                options:
                  - { label: "Izquierda", value: "left" }
                  - { label: "Derecha", value: "right" }
              - label: 'Listado'
                name: 'main_points'
                widget: 'list'
                fields:
                  - { label: Título, name: title, widget: string }
                  - { label: Texto, name: text, widget: text }
                  - { label: Ícono, name: icon, widget: string }